name: Facebook Live Stream

on: workflow_dispatch:

jobs: stream: runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v3
  
  - name: Install FFmpeg
    run: |
      sudo apt update
      sudo apt install -y ffmpeg
  
  - name: Start Facebook Live Stream
    run: |
      ffmpeg -re -i "https://cdn.live.easybroadcast.io:443/abr_corp/73_aloula_w1dqfwm/corp/73_aloula_w1dqfwm_480p/chunks_dvr.m3u8" \
      -c:v copy -c:a aac -strict experimental -f flv \
      "rtmps://live-api-s.facebook.com:443/rtmp/FB-122173967522313606-0-Ab3DkZyaWlgD9gFvfLR8GWip"

